name: Typecheck and Lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: lts

      - name: Install dependencies
        run: npm ci

      - name: Run Type Checking
        run: npm run typecheck

      - name: Run ESLint
        run: npm run lint
